language: c
dist: bionic

env:
    - SMVERSION=1.9
    - SMVERSION=1.10

matrix:
    fast_finish: true

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib lib32stdc++6

before_script:
    # Make directory for SourceMod
    - mkdir -p am/sm
    - cd am/sm
    - wget -q "http://www.sourcemod.net/latest.php?version=$SMVERSION&os=linux" -O sourcemod.tar.gz
    - tar -xzf sourcemod.tar.gz

    # Download git-helper script for generating defines, start him.
    - wget -q https://raw.githubusercontent.com/CrazyHackGUT/sm-plugins/master/git.sh
    - chmod +x git.sh
    - ./git.sh > addons/sourcemod/scripting/UAS.git.sp

    # Go to scripting directory, exec chmod
    - cd addons/sourcemod/scripting
    - chmod +x spcomp
    - chmod +x compile.sh

    # Copy plugins, create directory for builds
    - cp -Rf ${TRAVIS_BUILD_DIR}/scripting/* ./
    - mkdir -p UAS/optional

script:
    - ./spcomp $COMPILER_PARAMS UAS.git.sp UAS_Core.sp -E -oUAS/Core
    - ./spcomp $COMPILER_PARAMS UAS.git.sp UAS_Admin.sp -E -oUAS/optional/Admin

before_deploy:
    - export CUSTOM_POSTFIX=_$SMVERSION
    - mkdir -p $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/adons/sourcemod/{scripting,plugins/UAS,configs,translations}
    - mkdir -p $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/database/
    - cp -Rf $TRAVIS_BUILD_DIR/scripting/* $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/scripting/
    - cp -Rf UAS/* $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/plugins/UAS/
    - cp -Rf $TRAVIS_BUILD_DIR/configs/* $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/configs/
    - cp -Rf $TRAVIS_BUILD_DIR/translations/* $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/translations/
    - cp -Rf $TRAVIS_BUILD_DIR/database/* $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/database/
    - cd $TRAVIS_BUILD_DIR
    - wget --user=$HTTP_USER --password=$HTTP_PASSWORD $BASE_URL/travis.sh

deploy:
    - provider: script
      skip_cleanup: true
      script: bash travis.sh