language: c
dist: bionic

env:
    - SMVERSION=1.9
    - SMVERSION=1.10
    - SMVERSION=1.11

matrix:
    fast_finish: true

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib lib32stdc++6

before_script:
    # Make directory for SourceMod
    - mkdir -p am/sm
    - cd am/sm
    - wget -q "http://www.sourcemod.net/latest.php?version=$SMVERSION&os=linux" -O sourcemod.tar.gz
    - tar -xzf sourcemod.tar.gz

    # Download git-helper script for generating defines, start him.
    - wget -q https://raw.githubusercontent.com/CrazyHackGUT/sm-plugins/master/git.sh
    - chmod +x git.sh
    - ./git.sh > addons/sourcemod/scripting/UAS.git.sp

    # Go to scripting directory, exec chmod
    - cd addons/sourcemod/scripting
    - chmod +x spcomp
    - chmod +x compile.sh

    # Copy plugins, create directory for builds
    - cp -Rf ${TRAVIS_BUILD_DIR}/scripting/* ./
    - mkdir -p UAS/optional

script:
    - ./spcomp $COMPILER_PARAMS UAS.git.sp UAS_Core.sp -E -oUAS/Core
    - ./spcomp $COMPILER_PARAMS UAS.git.sp UAS_Admin.sp -E -oUAS/optional/Admin

before_deploy:
    - export FILENAME=sm_uas.${TRAVIS_COMMIT:0:7}.${SMVERSION}.tar.gz
    - export PACKAGE_PATH=${TRAVIS_BUILD_DIR}/../package
    - mkdir -p $PACKAGE_PATH/addons/sourcemod/{scripting,plugins/UAS,configs,translations}
    - mkdir -p $PACKAGE_PATH/database
    - cp -Rf $TRAVIS_BUILD_DIR/scripting/* $PACKAGE_PATH/addons/sourcemod/scripting/
    - cp -Rf UAS/* $PACKAGE_PATH/addons/sourcemod/plugins/UAS/
    - cp -Rf $TRAVIS_BUILD_DIR/configs/* $PACKAGE_PATH/addons/sourcemod/configs/
    - cp -Rf $TRAVIS_BUILD_DIR/translations/* $PACKAGE_PATH/addons/sourcemod/translations/
    - cp -Rf $TRAVIS_BUILD_DIR/database/* $PACKAGE_PATH/database/
    - cd $TRAVIS_BUILD_DIR
    - tar -cvf ../${FILENAME} ${PACKAGE_PATH}

deploy:
    - provider: script
      skip_cleanup: true
      script: curl "${API_URL}?secret_key=${API_KEY}&tags=SourceMod%20${SMVERSION}" -F "artifact=@./../${FILENAME}"
